services:
  - type: web
    name: myproject-backend
    env: python
    buildCommand: cd MyBackend && pip install -r ../requirements.txt
    startCommand: cd MyBackend && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
